// Generated by CoffeeScript 1.3.3
(function() {
  var Apps, Client, Entities, Identities, Organizations, Scopes, Sessions, TokenInfos, Users, request, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  request = require('request');

  _ = require('underscore');

  Users = require('./users');

  Sessions = require('./sessions');

  Entities = require('./entities');

  TokenInfos = require('./token-infos');

  Apps = require('./apps');

  Identities = require('./identities');

  Organizations = require('./organizations');

  Scopes = require('./scopes');

  module.exports = Client = (function() {

    function Client(endpoint, options) {
      this.endpoint = endpoint;
      this.options = options != null ? options : {};
      this.get = __bind(this.get, this);

      this["delete"] = __bind(this["delete"], this);

      this.put = __bind(this.put, this);

      this.patch = __bind(this.patch, this);

      this.post = __bind(this.post, this);

      this._reqWithData = __bind(this._reqWithData, this);

      this._handleResult = __bind(this._handleResult, this);

      this._cleanEndpoint = __bind(this._cleanEndpoint, this);

      this.endpoint = this._cleanEndpoint(this.endpoint);
      if (!(this.endpoint && this.endpoint.length > 0)) {
        throw new Error("Endpoint required");
      }
      _.defaults(this.options, {
        maxCacheItems: 1000,
        maxTokenCache: 60 * 10,
        timeout: 2000,
        clientId: null,
        bearerToken: null,
        headers: {}
      });
      this.cache = {};
      this.apps = this.apiClients = new Apps(this);
      this.entities = new Entities(this);
      this.identities = new Identities(this);
      this.organizations = new Organizations(this);
      this.scopes = new Scopes(this);
      this.sessions = new Sessions(this);
      this.tokenInfos = new TokenInfos(this);
      this.users = new Users(this);
    }

    Client.prototype._cleanEndpoint = function(endpoint) {
      if (!endpoint) {
        return null;
      }
      return endpoint.replace(/\/+$/, "");
    };

    Client.prototype._handleResult = function(res, bodyBeforeJson, callback) {
      var body;
      if (res.statusCode === 401 || res.statusCode === 403) {
        return callback(new errors.AccessDenied(""));
      }
      body = null;
      if (bodyBeforeJson && bodyBeforeJson.length > 0) {
        try {
          body = JSON.parse(bodyBeforeJson);
        } catch (e) {
          return callback(new Error("Invalid Body Content"), bodyBeforeJson, res.statusCode);
        }
      }
      if (!(res.statusCode >= 200 && res.statusCode < 300)) {
        return callback(new Error(body ? body.message : "Request failed."));
      }
      return callback(null, body, res.statusCode);
    };

    Client.prototype._reqWithData = function(method, path, data, actor, callback) {
      var headers,
        _this = this;
      headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      };
      if (this.options.bearerToken) {
        headers['authorization'] = "Bearer " + this.options.bearerToken;
      }
      if (this.options.clientId) {
        headers['X-ClientId'] = this.options.clientId;
      }
      if (actor && (actor.actorId || actor.id)) {
        headers['X-Act-As-ActorId'] = actor.actorId || actor.id;
      }
      _.extend(headers, this.options.headers);
      return request({
        uri: "" + this.endpoint + path,
        headers: headers,
        body: data ? JSON.stringify(data) : null,
        method: method,
        timeout: this.options.timeout
      }, function(err, res, body) {
        if (err) {
          err.status = res ? res.statusCode || 500 : 500;
          return callback(err);
        }
        return _this._handleResult(res, body, callback);
      });
    };

    Client.prototype.post = function(path, data, actor, callback) {
      return this._reqWithData("POST", path, data, actor, callback);
    };

    Client.prototype.patch = function(path, data, actor, callback) {
      return this._reqWithData("PATCH", path, data, actor, callback);
    };

    Client.prototype.put = function(path, data, actor, callback) {
      return this._reqWithData("PUT", path, data, actor, callback);
    };

    Client.prototype["delete"] = function(path, actor, callback) {
      var headers,
        _this = this;
      headers = {
        'Accept': 'application/json'
      };
      if (this.options.bearerToken) {
        headers['authorization'] = "Bearer " + this.options.bearerToken;
      }
      _.extend(headers, this.options.headers);
      return request({
        uri: "" + this.endpoint + path,
        headers: headers,
        method: 'DELETE',
        timeout: this.options.timeout
      }, function(err, res, body) {
        if (err) {
          err.status = res ? res.statusCode || 500 : 500;
          return callback(err);
        }
        return _this._handleResult(res, body, callback);
      });
    };

    Client.prototype.get = function(path, actor, callback) {
      var headers,
        _this = this;
      if (!callback) {
        callback = actor;
        actor = null;
      }
      headers = {
        'Accept': 'application/json'
      };
      if (this.options.bearerToken) {
        headers['authorization'] = "Bearer " + this.options.bearerToken;
      }
      if (this.options.clientId) {
        headers['X-ClientId'] = this.options.clientId;
      }
      _.extend(headers, this.options.headers);
      return request({
        uri: "" + this.endpoint + path,
        headers: headers,
        method: 'GET',
        timeout: this.options.timeout
      }, function(err, res, body) {
        if (err) {
          err.status = res ? res.statusCode || 500 : 500;
          return callback(err);
        }
        return _this._handleResult(res, body, callback);
      });
    };

    return Client;

  })();

}).call(this);
