// Generated by CoffeeScript 1.6.3
(function() {
  var Entities,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = Entities = (function() {
    function Entities(client) {
      this.client = client;
      this.createable = __bind(this.createable, this);
      this.get = __bind(this.get, this);
      if (!this.client) {
        throw new Error("client parameter is required");
      }
    }

    Entities.prototype.get = function(slugOrId, actor, cb) {
      if (cb == null) {
        cb = function() {};
      }
      return this.client.get("/entities/" + slugOrId, actor, cb);
    };

    Entities.prototype.createable = function(name, cb) {
      if (cb == null) {
        cb = function() {};
      }
      return this.client.get("/entities/createable/" + name, null, cb);
    };

    return Entities;

  })();

}).call(this);
