// Generated by CoffeeScript 1.3.3
(function() {
  var Identities,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = Identities = (function() {

    function Identities(client) {
      this.client = client;
      this.createOrValidate = __bind(this.createOrValidate, this);

      if (!this.client) {
        throw new Error("client parameter is required");
      }
    }

    Identities.prototype.createOrValidate = function(providerName, v1, v2, profile, actor, cb) {
      var data;
      if (cb == null) {
        cb = function() {};
      }
      data = {
        v1: v1,
        v2: v2,
        profile: profile
      };
      return this.client.post("/identities/" + providerName, data, actor, cb);
    };

    return Identities;

  })();

}).call(this);
