// Generated by CoffeeScript 1.6.2
(function() {
  var Scopes,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = Scopes = (function() {
    function Scopes(client) {
      this.client = client;
      this.get = __bind(this.get, this);
      this.all = __bind(this.all, this);
      if (!this.client) {
        throw new Error("client parameter is required");
      }
    }

    Scopes.prototype.all = function(cb) {
      if (cb == null) {
        cb = function() {};
      }
      return this.client.get("/scopes", null, cb);
    };

    Scopes.prototype.get = function(name, cb) {
      if (cb == null) {
        cb = function() {};
      }
      return this.client.get("/scopes/" + name, null, cb);
    };

    return Scopes;

  })();

}).call(this);
