// Generated by CoffeeScript 1.6.3
(function() {
  var Sessions,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = Sessions = (function() {
    function Sessions(client) {
      this.client = client;
      this.signInLocal = __bind(this.signInLocal, this);
      if (!this.client) {
        throw new Error("client parameter is required");
      }
    }

    Sessions.prototype.signInLocal = function(login, password, cb) {
      var data;
      if (cb == null) {
        cb = function() {};
      }
      data = {
        login: login,
        password: password
      };
      return this.client.post("/sessions", data, null, cb);
    };

    return Sessions;

  })();

}).call(this);
